IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\rcarter')
CREATE LOGIN [ELIBERATION\rcarter] FROM WINDOWS
GO
CREATE USER [ELIBERATION\rcarter] FOR LOGIN [ELIBERATION\rcarter]
GO
