IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\jmohmood')
CREATE LOGIN [ELIBERATION\jmohmood] FROM WINDOWS
GO
CREATE USER [ELIBERATION\jmohmood] FOR LOGIN [ELIBERATION\jmohmood]
GO
