IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\cbuscemi')
CREATE LOGIN [ELIBERATION\cbuscemi] FROM WINDOWS
GO
CREATE USER [ELIBERATION\cbuscemi] FOR LOGIN [ELIBERATION\cbuscemi]
GO
