IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\aludin')
CREATE LOGIN [ELIBERATION\aludin] FROM WINDOWS
GO
CREATE USER [ELIBERATION\aludin] FOR LOGIN [ELIBERATION\aludin]
GO
