IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\rdeevi')
CREATE LOGIN [ELIBERATION\rdeevi] FROM WINDOWS
GO
CREATE USER [ELIBERATION\rdeevi] FOR LOGIN [ELIBERATION\rdeevi]
GO
