IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\mcook')
CREATE LOGIN [ELIBERATION\mcook] FROM WINDOWS
GO
CREATE USER [ELIBERATION\mcook] FOR LOGIN [ELIBERATION\mcook]
GO
