IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\sreddy')
CREATE LOGIN [ELIBERATION\sreddy] FROM WINDOWS
GO
CREATE USER [ELIBERATION\sreddy] FOR LOGIN [ELIBERATION\sreddy]
GO
