IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\molano')
CREATE LOGIN [ELIBERATION\molano] FROM WINDOWS
GO
CREATE USER [ELIBERATION\molano] FOR LOGIN [ELIBERATION\molano]
GO
