IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\mtemp')
CREATE LOGIN [ELIBERATION\mtemp] FROM WINDOWS
GO
CREATE USER [ELIBERATION\mtemp] FOR LOGIN [ELIBERATION\mtemp]
GO
