IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\ywardak')
CREATE LOGIN [ELIBERATION\ywardak] FROM WINDOWS
GO
CREATE USER [ELIBERATION\ywardak] FOR LOGIN [ELIBERATION\ywardak]
GO
