IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\tpham')
CREATE LOGIN [ELIBERATION\tpham] FROM WINDOWS
GO
CREATE USER [ELIBERATION\tpham] FOR LOGIN [ELIBERATION\tpham]
GO
