IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\jtran')
CREATE LOGIN [ELIBERATION\jtran] FROM WINDOWS
GO
CREATE USER [ELIBERATION\jtran] FOR LOGIN [ELIBERATION\jtran]
GO
