IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\jmorgan')
CREATE LOGIN [ELIBERATION\jmorgan] FROM WINDOWS
GO
CREATE USER [ELIBERATION\jmorgan] FOR LOGIN [ELIBERATION\jmorgan]
GO
