IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\kgarrett')
CREATE LOGIN [ELIBERATION\kgarrett] FROM WINDOWS
GO
CREATE USER [ELIBERATION\kgarrett] FOR LOGIN [ELIBERATION\kgarrett]
GO
