IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\vvinayak')
CREATE LOGIN [ELIBERATION\vvinayak] FROM WINDOWS
GO
CREATE USER [ELIBERATION\vvinayak] FOR LOGIN [ELIBERATION\vvinayak]
GO
