IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\sdeckard')
CREATE LOGIN [ELIBERATION\sdeckard] FROM WINDOWS
GO
CREATE USER [ELIBERATION\sdeckard] FOR LOGIN [ELIBERATION\sdeckard]
GO
