IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\jwolfson')
CREATE LOGIN [ELIBERATION\jwolfson] FROM WINDOWS
GO
CREATE USER [ELIBERATION\jwolfson] FOR LOGIN [ELIBERATION\jwolfson]
GO
