IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\jnielsen')
CREATE LOGIN [ELIBERATION\jnielsen] FROM WINDOWS
GO
CREATE USER [ELIBERATION\jnielsen] FOR LOGIN [ELIBERATION\jnielsen] WITH DEFAULT_SCHEMA=[ELIBERATION\jnielsen]
GO
