IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\tcoulter')
CREATE LOGIN [ELIBERATION\tcoulter] FROM WINDOWS
GO
CREATE USER [ELIBERATION\tcoulter] FOR LOGIN [ELIBERATION\tcoulter]
GO
