IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\TCAMPBELL')
CREATE LOGIN [ELIBERATION\TCAMPBELL] FROM WINDOWS
GO
CREATE USER [ELIBERATION\TCAMPBELL] FOR LOGIN [ELIBERATION\TCAMPBELL]
GO
