IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ELIBERATION\wchang')
CREATE LOGIN [ELIBERATION\wchang] FROM WINDOWS
GO
CREATE USER [ELIBERATION\wchang] FOR LOGIN [ELIBERATION\wchang]
GO
