CREATE TABLE [dbo].[DB_2569_RowsToUpdate]
(
[Contact First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contact Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contact Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Address 1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Address 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Zip] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business category 1] [float] NULL,
[Business Category 2] [float] NULL,
[Business Tag Line] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Description] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hide Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Web Site URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Web Site Display URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Service] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brands Offered] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom Keyword(s)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area County 1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area State 1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area County 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area State 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area County 3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area State 3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area County 4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area State 4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area County 5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service Area State 5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mile Radius] [float] NULL,
[Year Established] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Employees] [float] NULL,
[Number of Locations] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Products Offered] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Specialty Products/Services] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language Spoken 1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language Spoken 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language Spoken 3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Offer URL 1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Offer URL 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_Cash] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_MC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_Visa] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_Check] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_Discover] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_AMEX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt_All CC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Senior/Child Discount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child Discount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Senior Discount ] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AAA Discount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AARP Discount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Government/Military Discount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chamber of Commerce Member] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBB Member] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other Associations] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Open 24 Hr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hide Hr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mon Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mon Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tues Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tues Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wed Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wed Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Thur Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Thur Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fri Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fri Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sat Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sat Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sun Open] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sun Close] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[By Appointment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserCID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Partner ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Partner Site ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Distribution Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Disposition] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pymt TypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesPersonID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Start Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[End Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription Cost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Alternate Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Category 3] [float] NULL,
[Business Category 4] [float] NULL,
[Business Category 5] [float] NULL,
[Business Category 6] [float] NULL,
[RID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrigKey] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lead CID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Login] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
