CREATE TABLE [dbo].[tblLM_listingorig_dupRID]
(
[TableKey] [int] NULL,
[AdvertiserID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[advertiserIDAX] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ListingID] [uniqueidentifier] NULL,
[ListingAX] [uniqueidentifier] NULL,
[RID] [int] NULL,
[RIDAX] [int] NULL,
[MasterAIDAX] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterRIDAX] [int] NULL,
[lMemberID] [int] NOT NULL,
[AgencyId] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgencyIDAX] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BldgName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unit] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip4] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lCountryID] [int] NOT NULL,
[LocationName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumberAlt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URL] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HideAddress] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sAction] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dtAction] [datetime] NOT NULL,
[dtListing1st] [datetime] NOT NULL,
[UpdatedBy] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tier] [int] NOT NULL,
[Bid] [int] NOT NULL,
[Latitude] [decimal] (9, 6) NULL,
[Longitude] [decimal] (9, 6) NULL,
[DtADD] [datetime] NOT NULL,
[BatchID] [int] NOT NULL,
[TitleSearch] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reason] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[tblLM_listingorig_dupRID] TO [lcssui]
GRANT SELECT ON  [dbo].[tblLM_listingorig_dupRID] TO [web_user]
GO
