SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[usp_LC_GET_Listing_By_ID]--@Listingid uniqueidentifier@TableKey intAS
SET TRANSACTION ISOLATION LEVEL   READ UNCOMMITTED
SET NOCOUNT ON
    SELECT          [TableKey]        ,[PartnerID]        ,[RLoad]        ,[dtAdd]        ,[SiteID]        ,[Distrib]        ,[Reason]        ,[RID]        ,[Ridax]        ,[UserCID]        ,[LeadCID]        ,[LeadOrigKey]        ,[AgencyLogin]        ,[HideAddress]        ,[SalePerson]        ,[SalePersonID]        ,[Status]        ,[Action]        ,[AdvertiserFirstName]        ,[AdvertiserLastName]        ,[ContactPhone]        ,[Email]        ,[CompanyID]        ,[CompanyName]		,[Address]        ,[City]        ,[State]        ,[ZipCode]        ,[Phone]        ,[AltPhone]        ,[BusEmail]        ,[BDCCategoryID]        ,[URL]        ,[DisplayURL]        ,[ClickURL]        ,[Title]        ,[TagLine]        ,[Description]        ,[LDACDescription]        ,[BusService]        ,[Brand]        ,[BusSpecialty]        ,[BeginSubscription]        ,[EndSubscription]        ,[Keywords]        ,[KeyCode]        ,[BDC1]        ,[BDC2]        ,[BDC3]        ,[BDC4]        ,[ServiceCounty]        ,[ServiceCountySt]        ,[ServiceCounty2]        ,[ServiceCountySt2]        ,[ServiceCounty3]        ,[ServiceCountySt3]        ,[ServiceCounty4]        ,[ServiceCountySt4]        ,[ServiceCounty5]        ,[ServiceCountyST5]        ,[Advertiserid]        ,[MemberID]        ,[OrderID]        ,[PymTypeID]        ,[billingMethod]        ,[Source]        ,[AdCost]        ,[CCLast4]        ,[MktCode]        ,[DispCode]        ,[Listingid]        ,[UpdatedBy]        ,[YearEst]        ,[NumEmployee]        ,[NumLocation]        ,[BusProduct]        ,[Language1]        ,[LanguageID1]        ,[Language2]        ,[LanguageID2]        ,[Language3]        ,[LanguageID3]        ,[URLSpecial1]		,[URLSpecial2]        ,[Pymt_Cash]        ,[Pymt_MC]        ,[Pymt_Visa]        ,[Pymt_Check]        ,[Pymt_Discover]        ,[Pymt_AMEX]        ,[Pymt_AllCC]        ,[SeniorChildDisc]        ,[ChildDisc]        ,[SeniorDisc]        ,[AAADisc]      
		,[AARPDisc]        ,[GovMilitaryDisc]        ,[ChamberofCommerce]        ,[BBB]        ,[OtherAssoc]        ,[Open24Hr]        ,[HideHr]        ,[MonOpen]        ,[MonClose]        ,[TusOpen]        ,[TusClose]        ,[WedOpen]		,[WedClose]
        ,[ThuOpen]        ,[ThuClose]        ,[FriOpen]        ,[FriClose]        ,[SatOpen]        ,[SatClose]        ,[SunOpen]        ,[SunClose]        ,[ByAppointment]        ,[BillingInterval]        ,[TitleSearch]FROM	
ListingEnhance.[dbo].[tblTM_UploadLDACImport]WHERE	[TableKey] = @TableKey
--[Listingid] = @Listingid
AND     [Reason] IS NOT NULL
GO
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [iisLpAdminFull]
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [iisLpAdminSsUiFull]
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [iisReviewEngine]
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [iisReviewEngineFull]
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [lcssui]
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [LocalConnect]
GRANT EXECUTE ON  [dbo].[usp_LC_GET_Listing_By_ID] TO [web_user]
GO
